language: python
python: 3.6
branches:
  only:
    - master
    - site
git:
  depth: false
cache: 
  directories:
    - $HOME/.cache/pip
    - /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages
    - /home/travis/virtualenv/python3.6.3/bin
install:
  - pip install mkdocs mkdocs-material
  - echo -e "machine github.com\n  login ${github_token}" > ~/.netrc
script:
  - mkdocs gh-deploy --clean
