language: python
python: 3.6
branches: master
cache: 
  directories:
    - $HOME/.cache/pip
    - /data
    - /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages
    - /home/travis/virtualenv/python3.6.3/bin
install:
  - pip install mkdocs mkdocs-material
  - echo -e "machine github.com\n  login ${github_token}" > ~/.netrc
  - cd /data
  - git clone https://github.com/ypwhs/dl-engineer-guidebook
script:
  - mkdocs gh-deploy
