language: python
python: 3.6
cache: pip
branches: master
install:
    - pip install mkdocs mkdocs-material
    - echo -e "machine github.com\n  login ${github_token}" > ~/.netrc

script:
  - mkdocs gh-deploy

branches:
  only:
    - master
